language: go

go: 1.11.x

# Don't grab any dependencies or whatnot, we're not building go-ipfs, rather
# forking the upstream one.
install: true

before_script:
  # Configure the SSH key to pull and push the repository
  - echo $GITHUB_PUSH_KEY | base64 -d > ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa

  # Clone the upstream IPFS repository to ungx
  - mkdir -p $GOPATH/src/github.com/ipfs
  - cd $GOPATH/src/github.com/ipfs
  - git clone --depth=1 https://github.com/ipfs/go-ipfs.git
  - cd go-ipfs

  # Install the necessary tools for ungx-ing and convert go-ipfs
  - go get github.com/whyrusleeping/gx
  - go get github.com/karalabe/ungx
  - ungx --fork=github.com/ipsn/go-ipfs

  # Save the latest commit hash and wipe all git history recursively
  - COMMIT=`git rev-parse HEAD`
  - find . -type d -name .git | xargs -d '\n' rm -rf

  # Save the ungx-ed readme to update the master branch with
  - cd $GOPATH/src/github.com/ipsn/go-ipfs
  - cp README.md ../README.md

  # Wipe the current ipsn/go-ipfs master and move in the freshly ungx-ed content
  - git remote add upstream git@github.com:ipsn/go-ipfs.git
  - git fetch upstream
  - git checkout master
  - git rm -r '*'
  - mv $GOPATH/src/github.com/ipfs/go-ipfs/{.[!.],}* .

  # Vendor in any dependencies missing in the first place
  - go get github.com/kardianos/govendor
  - govendor fetch +external

  # Overwrite the reposiory readme and commit all the changes
  - cp -f ../README.md README.md
  - rm .gitignore
  - git add .
  - if [ -n "$(git status --porcelain)" ]; then git commit --author="Péter Szilágyi <peterke@gmail.com>" -m "Ungx-ed commit $COMMIT"; fi

  # Sanity check that the repository can be built
  - go install ./cmd/...

script:
  # Everything seems ok, push the ungx-ed master branch back to GitHub
  - git push upstream master
